### PR TITLE
Make ilkName function public

### PR DESCRIPTION
**Pull request by gbalabasquer**

### CODE REVIEW

**Comment by asymmetric** [comment]
Missed the order 😂

**Comment by asymmetric** [comment]
I’m gonna make a change and then merge.

**Comment by gbalabasquer** [comment]
Sure!

**Comment by asymmetric** [comment]
Closed in https://github.com/makerdao/nft-adapter/commit/260b6b019f9ad5b9deb4561c7aa3595b4efbd559.

**Comment by asymmetric** [comment]
j

**Pull request closed without merging**
